global:
  scrape_interval: '1s'

scrape_configs:
  - job_name: 'api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      #- targets: ['host.docker.wsl:8080']
      #  labels:
      #    application: 'local-api'
      - targets: ['your-api1.com/api']
        labels:
          application: 'your-api1'
      - targets: [ 'your-api2.com/api' ]
        labels:
          application: 'your-api2'
